echo  "\n\n\n\n\t==============================================="
echo  "\t|Bem-vindo ao The Offspring                   |"
echo  "\t|O The Offspring é uma ferramenta de          |"
echo  "\t|softwares que cria comandos e executavéis    |"
echo  "\t|binários do Windows que são colocados em     |"
echo  "\t|dispositivos de armazenamento USB pen-drive  |"
echo  "\t|que são compilados quando inseridos.         |"
echo  "\t==============================================="
echo  "\t|O The Offspring permite automatizar a confi  |"
echo  "\t|guração de comandos e pré-compilar arquivos  |"
echo  "\t|necessários, além de automatizar o processo  |"
echo  "\t|de mover os arquivos.                        |"
echo  "\t==============================================="
echo  "\n\n"
echo  "\t---------------------------------------------"
echo  "\tEssa ferramenta é somente para fins educacionais."
echo  "\tO autor não é responsavél pelo que você faz com"
echo  "\tessa ferramenta."
echo  "\t--------------------------------------------"
echo  "\tDesenvolvido por: @gb.mps7 (Instagram)"
echo  "\tgabriel.mpsouza@aluno.educacao.pe.gov.br\n"
